### ISSUE TITLE
Neptune 4 Pro - Bad Request

### ISSUE THREAD

**Issue by ChuckMac** [sandmmakers/BedLeveler5000#48]
Trying to run BL5K on my Neptune 4 Pro.  I can connect to the printer, set temperature, and probe point 1.  However when I attempt to probe any other points I get a "Bad Request" error and it disconnects from the printer.  Fluidd console is showing "Move out of range".

This is v0.4.0 on Windows

![image](https://github.com/sandmmakers/BedLeveler5000/assets/1966834/11b0a81a-2849-465a-aa07-9be826c870d2)

![image](https://github.com/sandmmakers/BedLeveler5000/assets/1966834/82e9ff3c-338f-4551-9286-9115a3cda5f9)

**Comment by sandmmakers** [comment]
Thank you for creating the bug report. Can you please upload a log file? Directions are available here: https://github.com/sandmmakers/BedLeveler5000/blob/master/Docs/FilingABugReport.md

**Comment by ChuckMac** [comment]
Thank you for the quick response. 

So after restarting in debug mode the issue went away.  Going to chalk it up to user error.

Thanks a lot for all your work on this!
