### ISSUE TITLE
Improve comments and documentation

### ISSUE THREAD

**Issue by sandmmakers** [sandmmakers/BedLeveler5000#5]
The comments and documentation for Bed Leveler 5000 are currently lacking and need to be improved.

**Comment by benjaminnestler** [comment]
Hopefully that's the right issue for a small documentation change ;-)

I've build the bedleveler5000 from the sources.

You should change the `git clone` part of your windows/unix description because you use submodules.

So the correction should be `git clone <your repo> --recurse-submodules`
