### ISSUE TITLE
the probe H is going in wrong position

### ISSUE THREAD

**Issue by ctc0sma** [sandmmakers/BedLeveler5000#50]
the probe H is going in wrong position in neptune 3 max . the home is going to the centre but the H button no
HOME BUTTON
![20240127_122813](https://github.com/sandmmakers/BedLeveler5000/assets/93996055/a90badeb-5289-43e3-b910-23bee1f73b07)

H BUTTON (Probe H)
![20240127_122829](https://github.com/sandmmakers/BedLeveler5000/assets/93996055/f2fe0c49-904a-4a58-8544-8f5e4cce30f6)

**Comment by sandmmakers** [comment]
The Neptune 3 Max configuration is setup to probe the same locations the nozzle is directed to during manual leveling using the LCD controller.
