### ISSUE TITLE
Error M420

### ISSUE THREAD

**Issue by altcontroldelete22** [sandmmakers/BedLeveler5000#55]
Trying to connect to my Neptune 3 Max with BL5 and i am getting a error message failed to parse the m420 output
![Screenshot_1](https://github.com/sandmmakers/BedLeveler5000/assets/160540580/ee27f0d0-f4b1-434b-b442-4abf0a2f89f7)
![Screenshot_2](https://github.com/sandmmakers/BedLeveler5000/assets/160540580/1bafa411-2227-407e-b4f6-5664e5fd0cda)

**Comment by sandmmakers** [comment]
Thank you for creating the ticket. Can you please create a log file and add it to this ticket? The directions for creating a log file are in the "How to file a bug?" page int eh documentation. Without a log file, I can't really say what is causing the problem.

**Comment by sandmmakers** [comment]
I just noticed that you are using an older version of BL5K. Please try using version v0.5.0. I think the issue might be that you don't have a mesh loaded in your printer. BL5K used to have a descriptive error message for this situation, but there was a regression in version v0.4.0, where the error was properly detected, but the error message wasn't as helpful as it could be. Version v0.5.0 restores the more helpful error message.

**Comment by altcontroldelete22** [comment]
Hello, thank you for your timely response. Attached is the log file: hxxps[:]//pastebin[.]com/rQygvaGC

**Comment by altcontroldelete22** [comment]
[log.log](https://github.com/sandmmakers/BedLeveler5000/files/14338105/log.log)

**Comment by altcontroldelete22** [comment]
![Screenshot_3](https://github.com/sandmmakers/BedLeveler5000/assets/160540580/1162482a-58bd-4761-a7d1-09107a26d903)

**Comment by sandmmakers** [comment]
Thank you for the log and trying version v0.5.0. It appears that your printer currently doesn't have a mesh. Please run ABL and then try again.

**Comment by altcontroldelete22** [comment]
im getting the same error message
just ran abl twice

**Comment by sandmmakers** [comment]
You performed ABL using the printer's LCD controller?

**Comment by altcontroldelete22** [comment]
yes sir

**Comment by sandmmakers** [comment]
Did you disconnect BL5K before performing ABL and then reconnect after ABL was complete? If so, then something is very strange.

**Comment by altcontroldelete22** [comment]
give me a second , going to re run it now

**Comment by sandmmakers** [comment]
In the provided log file, your printer is reporting that the mesh is either missing or bad. You can test it by connecting to your printer with the Inspector G-code utility and issuing a `M420 V` command.

**Comment by altcontroldelete22** [comment]
![Screenshot_4](https://github.com/sandmmakers/BedLeveler5000/assets/160540580/08371926-f316-43fd-947d-44a56d01542d)

**Comment by sandmmakers** [comment]
I'm creating a mesh on my Neptune 3 Max and then I will test just to make sure the code is working properly. However, my guess is that there is something wrong with your printer.

**Comment by altcontroldelete22** [comment]
Ok thank you.

**Comment by sandmmakers** [comment]
I powered on my printer, went to the leveling screen, clicked measure, let ABL complete, navigated back to the main/home screen, and then issues the `M420 V` command in Inspector G-code and got the expected mesh output.

**Comment by sandmmakers** [comment]
This is what the output of the `M420 V ` command should be: 
![image](https://github.com/sandmmakers/BedLeveler5000/assets/145303647/7cbd0e1e-3beb-436a-8fc1-2df6d5cc865b)

**Comment by sandmmakers** [comment]
When you perform ABL, do all of the mesh values appear on the LCD screen? If you are not able to create a mesh then I'm really not sure what else to suggest except to contact Elegoo at 3dp@elegoo.com. A this point, we are just testing the Elegoo provided firmware and since it is Marlin, there is really nothing to tweak or change.

**Comment by altcontroldelete22** [comment]
no it stops at the 4th probe and gives me the probing failed screen on the lcd

**Comment by altcontroldelete22** [comment]
yes i just contacted them,,, unbelievable

**Comment by altcontroldelete22** [comment]
![Screenshot_5](https://github.com/sandmmakers/BedLeveler5000/assets/160540580/d57c9307-cc5f-4815-ad06-b3d225b316d5)

**Comment by altcontroldelete22** [comment]
allright !!

**Comment by altcontroldelete22** [comment]
![Screenshot_5](https://github.com/sandmmakers/BedLeveler5000/assets/160540580/642d94c5-f669-4054-9f36-572fda940b1d)

**Comment by altcontroldelete22** [comment]
![Screenshot_6](https://github.com/sandmmakers/BedLeveler5000/assets/160540580/8dcb379a-cb9b-4009-8a5f-16ff67473d1e)

**Comment by sandmmakers** [comment]
Fantastic! You got it to work!! What was the problem?
