### ISSUE TITLE
Fixed Reference not always as chosen

### ISSUE THREAD

**Issue by mtc1122** [sandmmakers/BedLeveler5000#57]
Neptune 4 Plus
Windows 64 bit

Initially chose
Reference: H
Direction: CW
Output: Degrees

Probed 1 ( 35.0,  24.0):  0.211 (Fixed reference)
Probed 2 ( 35.0, 155.0):  0.189 (Adjust:  11.57° CW)
Probed 3 ( 35.0, 290.0):  0.159 (Adjust:  27.00° CW)
Probed 4 (290.0, 290.0):  0.139 (Adjust:  37.29° CW)
Probed 5 (290.0, 155.0):  0.144 (Adjust:  34.71° CW)
Probed 6 (290.0,  35.0):  0.154 (Adjust:  29.57° CW)
Probed H (162.5, 162.5):  0.125

As you can see, for some reason it chose 1 as the fixed reference.

Running the above with Any, or CCW gives me this
Probed 1 ( 35.0,  24.0):  0.266 (Adjust:  44.36° CCW)
Probed 2 ( 35.0, 155.0):  0.226 (Adjust:  23.79° CCW)
Probed 3 ( 35.0, 290.0):  0.209 (Adjust:  14.79° CCW)
Probed 4 (290.0, 290.0):  0.196 (Adjust:   8.36° CCW)
Probed 5 (290.0, 155.0):  0.195 (Adjust:   7.71° CCW)
Probed 6 (290.0,  35.0):  0.213 (Adjust:  16.71° CCW)
Probed H (162.5, 162.5):  0.180 (Fixed reference)

It seems that the issue may have to do with choosing the direction that's opposite what is suggested.

**Comment by sandmmakers** [comment]
The direction option takes precedence over the the reference option. When the direction is set to anything other than `Any`, the reference option combo box is disabled.
